apiVersion: v1
kind: Service
metadata:
  name: viewer
  labels:
    app: mlmd-bom-output-reader
spec:
  selector:
    app: mlmd-bom-output-reader
  ports:
    - name: http
      port: 5173
      targetPort: 5173
      protocol: TCP
  type: ClusterIP
